### ISSUE TITLE
Rename "Popochiu" example game

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#11]
This is trivial/low priority, but the example game inside the `popochiu-dev` repository is itself named "Popochiu" and sports the same string everywhere. This makes things a bit confusing for first-time contributors. It also makes it harder to search inside the repo (even if excluding the game folder is actually an easy solution).  
The fact that  the engine's logo also matches the characters' apperance makes it worse :)

We can rename the example game and try to exclude the work "Popochiu" in it.

**Comment by mapedorr** [comment]
There is one thing that worries me about this. I'm using that popochiu folder to check if the plugin is ready to be used. When it is installed, the plugin creates the folder and put some files there (including `PopochiuData.cfg`, `PopochiuSettings.tres`, and `PopochiuGlobals.gd`). Then when Godot starts the plugin checks if the folder exists, and if it does, then it continues with all the logic for the Popochiu dock.

One option is to get rid of the popochiu folder and make all those configuration files and the folders for rooms, characters, inventory items and dialog trees to be in the project's root: `res://`.

Maybe another option is to ask devs how they want to name the folder and store that in the `PopochiuData.cfg` for later validations.

**Comment by stickgrinder** [comment]
The game folder has been long renamed `game` and this is no more an issue. Closing
