### ISSUE TITLE
Better dialogue system with localization

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#16]
Current Popochiu dialogue system is pretty limited. The goal is to introduce a more complete and full-featured one, with the following features:

* **Good localization support**, ideally based on GetText and po files which are industry standard and allow translators to use serious tools like POEdit instead of spreadsheets. CSVs are still a nice addition, tho.
* **Not limited to dialogues**: starting a dialogue should allow the dev to just fire a complete, full-featured Popochiu script, allowing for everything from state changes, to cutscenes, to animations. Declarative dialogues are easy to jot down but very limited in scope.
* **Smooth integration with the GUI subsystem**, allowing the devs to customize dialogue interactions the way they see fit, for example using icons instead of text for dialogue navigation (much like _Sam&Max Hit the Road_) or inventing new patterns. Ideally the dialogue system should be unopinionated about how a dialogue script is triggered or shown to the user.
* **Strong decoupling** from other engine featues, so that there are no strict dependencies in the engine.

There are two good inspirations to draw from:

### [Dialogue Manager 2.0 addon](https://www.youtube.com/watch?v=DL79aS-dT7E)

**Pros**:
* based on an easy-to-understand DSL, with specific, well-integrated file format
* built-in localization support (both CSV and PO)
* less than 2000 lines of code and very well integrated with the editor
* may be more than an inspiration for just the dialogue system and inspire a full Popochiu scripting interpreter (I may regret writing this :smile: )

**Cons**:
* there are overlaps with game scripting that may end up distributing code between dialogs and other parts of the game scripts
* a bit too opinionated
* partly declarative, partly "touring-complete" approach
* lacking dependency management, using it directly in Popochiu is impossible, we should rewrite our version of it

### [PowerQuest dialogue system](https://www.youtube.com/watch?v=ioMPeNBAg0Y)

**Pros:**
* Very loosely coupled with other framework systems, it's basically just a very convenient way to catalog lines or icons that trigger game scripts in a dedicated GUI
* Powerful API allowing for inline dialogs, return values to branch script execution, catalogs inspection and more
* Good editor UI to manage dialogues catalogs

**Cons**:
* Localization (as a whole) is working but "fragile", based on source files scraping (it got better over time and I consider it stable ATM)
* Localization doens't support multiple languages voiceover
* Localization does not use uuids for strings, makes it hard to re-process the whole game in various phases, making it easier to introduce error without spotting them
* Editor UI is easy but a bit cumbersome. It may be a pain for large games and it's not an option (Unity prefab, you can edit YAML yourself but at your own risk - :skull_and_crossbones: )

**Comment by mapedorr** [comment]
What are dialogue catalogs and catalogs inspection?

**Comment by stickgrinder** [comment]
This issue must be split in two separate parts: localization is a broader topic than dialogs.

**Comment by stickgrinder** [comment]
Maybe a duplicate of #42 ; I'll check and close if it's the case.

**Comment by stickgrinder** [comment]
Everything mentioned in this issue is already done. An issue to improve the UX of dialog items is already filed (#260) as well as one for the localization support (#40)

Closing this epic
