### ISSUE TITLE
Can't block interactions

### ISSUE THREAD

**Issue by mapedorr** [carenalgas/popochiu#166]
### Bug description

When `PopochiuCharacter.walk_to_clicked` is called, there's no way to block interactions until the action finishes, which causes undesired behaviors.

###  Steps to reproduce

1. Create a Hotspot and make the character walk to it when clicked and then say something.
2. Run the game and click the created Hotspot.
3. While the character is moving towards the Hotspot, click elsewhere.
4. The character will move to the last clicked position, and after that will say the dialogue line scripted for the Hotspot.

### Expected vs observed behavior

There should be a way to block interactions when `PopochiuCharacter.walk_to_clicked` is called. Maybe the default behavior should block interactions, or maybe there should be an alternate method like `PopochiuCharacter.walk_to_clicked_blocking`.

### Environment information (please complete):

 - **OS type and version**: Windows 11
 - **Godot version**: 4.2.1
 - **Plugin version or branch**: beta 1

**Comment by stickgrinder** [comment]
Closed in #172
