### ISSUE TITLE
Hover text and Cursor are wrong after interaction

### ISSUE THREAD

**Issue by mapedorr** [carenalgas/popochiu#170]
### Bug description

When a hotspot or prop or character is clicked, the cursor keeps showing its hover text even though it comes out of its InteractionPolygon. Same for the cursor, which keeps showing the "active" animation (in the 2-click Context-sensitive GUI).

Thanks to **_antecanis78_** for reporting the bug in Discord and providing us the video.

###  Steps to reproduce

Using the 2-click Context-sensitive GUI.

1. Create a room with a hotspot and make the player say something when it is clicked.
2. Play the game and move the mouse over the hotspot. The HoverText will show its description and the cursor will play the "active" animation.
3. While the character is saying its dialogue line, move the cursor out of the hotspot.
4. The HoverText will keep showing the description of the hotspot, and the cursor will still play the "active" animation, even though the cursor is not hovering the object.

### Expected vs observed behavior

The HoverText should change if the cursor leaves the hotspot. The cursor should go back to its "normal" state too.

https://github.com/carenalgas/popochiu/assets/4536477/4d8f1870-8c59-4064-accc-45b8f92bac25

### Environment information (please complete):

 - **OS type and version**: Windows 11
 - **Godot version**: 4.2.1
 - **Plugin version or branch**: Beta 1

**Comment by stickgrinder** [comment]
Fixed in #172
