### ISSUE TITLE
Template change issue

### ISSUE THREAD

**Issue by mefjak** [carenalgas/popochiu#178]
### Bug description

There is issue when I want to change template.

###  Steps to reproduce

1. On first setup choose 2-click template
2. add room, character, walkable area, assign character to the room
3. click setup

### Expected vs observed behavior

There should be 4 templates but every second click there are only 2

### Environment information (please complete):

 - MacOS Sonoma 14.2.1 (M1)
 - Godot 4.2.1
 - Popochiu 2 Beta 2 

https://github.com/carenalgas/popochiu/assets/22888465/9a24eb88-4788-4b79-bfa4-f1deaa280503

**Comment by mapedorr** [comment]
Thanks for reporting the bug. I'll work on it tomorrow.
