### ISSUE TITLE
New Documentation - Point the project README to the new documentation

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#186]
### Benefit description

Despite not being stable ATTOW, the current promoted version of Popochiu is 2.0.

The project README still points to the wiki as a source for documentation, and this is generating confusion.
It's better to change the link so that it points to the new docs. It can be done immediately or right after having #185 ready, probably with comparable negative impacts (wait a bit longer or point to an incomplete doc).

**Comment by mapedorr** [comment]
What do you mean here? Because this one is already directing to the new website of the documentation.

![image](https://github.com/carenalgas/popochiu/assets/4536477/91a59a99-750c-4269-b4bd-97202be4ea34)

**Comment by stickgrinder** [comment]
I mean that I am dumb... I'm going to close this :facepalm:
