### ISSUE TITLE
Gibberish text for dialog options and spoken text

### ISSUE THREAD

**Issue by mefjak** [carenalgas/popochiu#217]
### What's the expected benefit of the feature you are requesting?

I have seen this on one of a game developers streams of his work and he didn't want to show dialogs between characters, he used that option to hide all text between them.

### Describe the solution you'd like

After turning specific project options, all text would be changed to gibberish.
For example : 
- "Hello" => "klabt"
- "[wave]bye bye[/wave] => "[wave]hjk wqm[/wave]

https://github.com/carenalgas/popochiu/assets/22888465/1f51993e-fb52-441f-ab50-8aed0d096063

**Comment by mapedorr** [comment]
Closed with #218
