### ISSUE TITLE
Add support for viewport-drawn gizmos for PopochiuClickable properties

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#232]
### Benefit description

Currently, the gizmos connected to PopochiuClickable objects are implemented as hidden nodes in the object themselves.

For example, the WalkTo point is chosen by a rectangle element that is selected by a button in the toolbar.

TODO: finish the description o this issue, providing animated gifs.

### Solution description

TODO: describe the solution and provide links to the source material

### Exclusions

Markers are not clickable, but they have to be positioned on the scene, so they are candidates for gizmos too.
This issue only takes into consideration PopochiuClickable objects, with gizmos for points and baselines.

### Implications

TODO

### Done when

* [x] The gizmo to position the "Walk To Point" is drawn as a rectangle on the viewport
* [x] The gizmo to position the "Baseline" is drawn as a line with a square handle on the viewport
* [x] The relevant properties for the visual representation of the gizmos are configurable as "Editor Settings":
  * [x] Size of the handles
  * [x] Colors of the handles
  * [x] Visibility of the clickable node name labels
  * [x] Outline visibility
  * [x] Connectors visibility
* [x] ~~A button is available in the Clickables toolbar to hide or show the gizmos (all of them)~~ (split in #134)
* [x] The gizmos actually update the properties they are linked to
* [x] The old gizmos implemented as node helpers should be removed from Props, HotSpots and Characters
* [x] Update documentation (change screenshot and description in "Getting Started / Create game stub" section of the docs)
* [x] Change DialogPos from Marker2D to a position gizmo
* [x] We have an upgrade path (see #227) to:
    * [x] remove the node helpers in every Popochiu object for projects that already have them
    * [x] ~~add `POPOCHIU_OBJ_POLYGON_GIZMO` meta to every polygon in the popochiu objects that have one~~ (no more relevant, we implemented this with groups set at runtime)

**Comment by drbbgh** [comment]
Character properties such as `baseline` and `walk_to_point` coordinates should be visible in the inspector for character instances in the room.
Also, `walk_to_point` coordinates should be integers (see [Vector2i](https://docs.godotengine.org/en/stable/classes/class_vector2i.html)).

**Comment by stickgrinder** [comment]
This became related to #134 and has been moved for release with Popochiu 2.0 (cc @drbbgh @mapedorr )
