### ISSUE TITLE
Setting a hotspot's property Clickable to false does not take an effect

### ISSUE THREAD

**Issue by fhgaha** [carenalgas/popochiu#249]
### Bug description

Setting a hotspot's property Clickable to false does not take an effect

###  Steps to reproduce

1. Create a hotspot
2. In the hotspot method `_on_click()` set property `clickable = false` 
3. Watch the hotspot still being clickable in runtime even after being clicked the first time

### Expected vs observed behavior

Should become not clickable

### Environment information (please complete):

 - Windows 10
 - 4.2.2: 
 - develop branch commit:

**Comment by mapedorr** [comment]
Thanks for reporting the bug. We'll give it a look.

**Comment by mapedorr** [comment]
This was actually affecting all PopochiuClickable objects. It is now fixed by #254 ,
