### ISSUE TITLE
Confusing Setup: Can't set native game resolution or playing window resolution via keyboard

### ISSUE THREAD

**Issue by XaverStiensmeier** [carenalgas/popochiu#251]
### Bug description

I can't enter width and height via keyboard in the setup window: 
![grafik](https://github.com/user-attachments/assets/54c6b98f-db48-4a78-a0c3-f950abb8933f)
I can only change the values by clicking the tiny arrows, but that's not really feasible for bigger changes.

This might be caused by https://github.com/carenalgas/popochiu/issues/250 but for now I think it is a different issue.

###  Steps to reproduce

1. Install popchiu
2. Restart
3. Try to enter something via keyboard in to the width and height fields in setup

### Expected vs observed behavior

I expect to be able to change that value via keyboard

### Environment information (please complete):

 - **OS type and version**: Win11
 - **Godot version**: 4.2.2
 - **Plugin version or branch**: 2.0

**Comment by mapedorr** [comment]
Thanks. We'll double check, because here I tested in a new project and it allowed me to change those values with the keyboard.

https://github.com/user-attachments/assets/a00e308e-3987-48a4-a002-b80e8edc1d44

**Comment by XaverStiensmeier** [comment]
Interesting. I use a German keyboard layout (QWERTY), but I don't think that should affect that.

**Comment by stickgrinder** [comment]
Hi @XaverStiensmeier. I just tested the setup window on my development PC (Linux/Plasma) and typing a numeric value in there works flawlessly.

I wonder if you can't type anything at all in that fields or if you are trying to use your arrow keys to raise or lower the values. That one would not work, in fact.

Sorry for the silly question, but it's worth asking I guess.

**Comment by stickgrinder** [comment]
I'm going to close this as we can't replicate the error and we got no other recorded cases for that.
Also #258 will be on its way soon, so it will soon become irrelevant because the setup window will change heavily.

@XaverStiensmeier please, feel free to follow-up in case you have something to add.
