### ISSUE TITLE
Popochiu settings are moved to Project Settings

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#26]
At the moment, the plugin settings are exposed in the inspector as a set of resource properties, because it was quicker than creating a dedicated interface.

![immagine](https://user-images.githubusercontent.com/625436/216775977-733ee0b7-3850-4c61-88c5-805b71484b7f.png)

Having those exposed in the Project Settings would be sexier though (and sexier is better than quickier).

**Comment by mapedorr** [comment]
It would be nice to have sections: things related to the GI, things related to localization, things that will affect rooms, characters, and so on.
