### ISSUE TITLE
Link in Readme is dead

### ISSUE THREAD

**Issue by XaverStiensmeier** [carenalgas/popochiu#293]
Your link for 2.0 at "Compatibility chart" is dead: `https://github.com/carenalgas/popochiu/releases/download/v2.0/popochiu-v2.0.0.zip` on  is dead. I think it should be: `https://github.com/carenalgas/popochiu/releases/download/v2.0.0/popochiu-v2.0.0.zip` instead (it misses a .0 at the first 2.0.

**Comment by mapedorr** [comment]
Thank you. We'll fix it.
