### ISSUE TITLE
Room contents is playing before  _on_room_entered()  has executed when no transition is enabled

### ISSUE THREAD

**Issue by balloonpopper** [carenalgas/popochiu#348]
### Bug description

This function is supposed to run when "the room is in the tree but it is not visible".
If you change room with no transition (e.g. "R.goto_room("Locker", false)") then you can see the contents of the new room ("Locker") briefly while its _on_room_entered() function executes. I can tell this as I have calls in _on_room_entered() to disable various things
e.g. 
```
	if C.player.state.WearingTowel == false:
		R.get_prop("Towel").show()
		R.get_prop("Uniform").hide()
```
The Uniform prop displays for a brief period before disappearing.

###  Steps to reproduce

1. Create a room with a prop
2. In its _on_room_entered() function, hide the prop
3. Create a second room, with a "goto_room" function in it that takes you to the first room without a transition
4. Play the game. Observe when you move from the second room to the first room that the prop displays temporarily before disappearing

### Expected vs observed behavior

Everything in _on_room_entered should complete before the room is drawn to the screen

### Environment information (please complete):

 - Windows 10
 - 4.3 dev 3
 - Latest development branch of Popo

**Comment by mapedorr** [comment]
I'll take a look on this.
