### ISSUE TITLE
Migrations manager issue under 4.4 dev 5

### ISSUE THREAD

**Issue by balloonpopper** [carenalgas/popochiu#356]
### Bug description

My 4.4 project seems to be unhappy on 4.4 dev 5 - it keeps trying to run the migrations manager. The migrations manager either doesn't run, or doesn't have issues on 4.4 dev 4.
```
  scene/main/window.cpp:951 - Attempting to make child window exclusive, but the parent window already has another exclusive child. This window: /root/@EditorNode@18000/@Panel@13/@VBoxContainer@14/DockHSplitLeftL/DockHSplitLeftR/DockHSplitMain/DockHSplitRight/DockVSplitRightL/DockSlotRightBL/Popochiu/@AcceptDialog@18377, parent window: /root, current exclusive child window: /root/@ProgressDialog@18352
  Attempt to open script 'res://addons/popochiu/migration/migrations/popochiu_migration_4.gd' resulted in error 'File not found'.
  Failed loading resource: res://addons/popochiu/migration/migrations/popochiu_migration_4.gd. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/popochiu/migration/migrations_manager.gd:32 - Attempt to call function 'new' in base 'null instance' on a null instance.
```

###  Steps to reproduce

Open a project in 4.4 dev 5

### Expected vs observed behavior

Migrations manager shouldn't run for a Popo v2 project.

### Environment information (please complete):

 - Windows 10
 - 4.4 dev 5
 - Latest

### Additional context

My best guess (I'm not sure how to force the migrations manager to run to debug it) is that this function
```
static func get_migrations_count() -> int:
	return DirAccess.get_files_at(MIGRATIONS_PATH).size()
```
returns different results in 4.4 dev 4 to 4.4 dev 5.

**Comment by stickgrinder** [comment]
Closed without fix for we are not addressing dev versions of Godot.
