### ISSUE TITLE
Create repositories for demo projects

### ISSUE THREAD

**Issue by mapedorr** [carenalgas/popochiu#45]
This can be useful for newcomers, as they will be able to check those projects in order to know how to make things. Each project could be complemented with a face-paced video showing the creation process.

- [ ] A project that shows how to solve a puzzle by combining inventory items and having a dialog with another character (this could be just an update of the [current demo project](https://github.com/mapedorr/popochiu-demo) (which is very outdated)).
- [ ] A project that shows how to make a Myst-like point n' click game.

Ideas are welcome

**Comment by stickgrinder** [comment]
We created a repo for the demo project, even if it is not that pervasive.

I feel it needs a bit more thinking, but this issue was for 1.10: I think it's a bit outdated, and new documentation can better address these needs.

I'm going to close this and the related milestone, so we keep things tidy.
